### ISSUE TITLE
Generations management

### ISSUE THREAD

**Issue by louis-mtyr** [louis-mtyr/game_of_life-louis_martyr-CDOF4#1]
Keep track of the generations the game is at, and add a way to choose a specific max generation at which the game will stop at.

**Comment by swanjln** [comment]
I suggest introducing a "generation counter" feature to keep track of the number of generations elapsed since the start of the Game of Life simulation. Additionally, it would be highly beneficial to allow users to set a specific "max generation" limit, at which point the game would automatically stop.

This enhancement would not only add an educational aspect by allowing users to observe the evolution of patterns over specific intervals but also provide more control over the simulation's duration, making experimentation and analysis more convenient.

Implementing a user-prompt at the beginning for setting the max generation, along with a visible counter during the simulation, could achieve this effectively. This feature would greatly enrich the user experience and the educational value of the Game of Life simulation.
